#Build stage

FROM gradle:jdk17-alpine AS BUILD
COPY --chown=gradle:gradle . /home/gradle
COPY build.gradle settings.gradle gradlew .
COPY src .
COPY gradle .

ARG ARG_USERNAME
ARG ARG_TOKEN
ENV GPR_USERNAME=${ARG_USERNAME}
ENV GPR_TOKEN=${ARG_TOKEN}

RUN ./gradlew build

# Package stage

FROM yti-docker-java17-base:corretto
COPY --from=BUILD /home/gradle/build/libs/yti-datamodel-api.jar yti-datamodel-api.jar
ENTRYPOINT ["/bootstrap.sh", "yti-datamodel-api.jar", "-j", "-Djava.security.egd=file:/dev/./urandom"]
